# **Bioinformatics Project | Computational Drug Discovery | Part-3**

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

**What is PubChem?**

PubChem is a massive chemical database maintained by the NIH. Among many things, PubChem defines a standard fingerprint scheme:

881 fingerprint bits. Each bit corresponds to a specific chemical pattern.

For example:
```bash
Bit 1  -> Aromatic ring present?
Bit 2  -> Alcohol group present?
Bit 3  -> Amine present?
...
Bit 881 -> Some specific structural pattern
```

PubChem defines what the bits mean.

**What is PaDEL?**

PaDEL-Descriptor is software that reads a molecule and calculates descriptors/fingerprints.

Think:
```bash
SMILES
   ↓
PaDEL
   ↓
Features
```

PaDEL can calculate:
```bash
Lipinski descriptors
Topological descriptors
Electronic descriptors
Geometrical descriptors
PubChem fingerprints
MACCS fingerprints
Substructure fingerprints
```
and many others.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data/acetylcholinesterase_02_bioactivity_data_3class_pIC50.csv')

In [3]:
# Create SMILES file
df[['canonical_smiles']].to_csv(
    'Data/molecule.smi',
    sep='\t',
    index=False,
    header=False
)

Go inside the folder `PaDEL-Descriptor` (after unzipping `padel.zip`) and open cmd. Type the following command to generate the descriptors

```bash
java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PubchemFingerprinter.xml -dir <folder containing .smi file(e.g., F:\BioInformatics\main\Data)> -file <path to the output file(e.g., F:\BioInformatics\main\Data\descriptors_output.csv)>
```

In [13]:
df_desc = pd.read_csv('Data/descriptors_output.csv')
df_desc

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_molecule_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_molecule_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_molecule_3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_molecule_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_molecule_5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7169,AUTOGEN_molecule_7171,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7170,AUTOGEN_molecule_7170,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7171,AUTOGEN_molecule_7173,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7172,AUTOGEN_molecule_7172,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7173,AUTOGEN_molecule_7174,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
x = df_desc.drop(columns= ['Name'])
y = df['pIC50']

dataset = pd.concat([x, y], axis= 1)
dataset

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.124939
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.522879
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7169,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.318759
7170,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.397940
7171,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.954677
7172,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.283997
7173,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8.583359

In [17]:
dataset.to_csv('Data/acetylcholinesterase_03_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)